site_name: Polgraw group   

pages:
- Home: 'index.md'
- Pipeline description:
    - 'Input data generation': 'input_data.md'
    - 'Grid generation': 'grid_generation.md'
    - 'F-statistic candidate signal search': 'search_for_candidates.md'
    - 'Coincidences between candidates': 'coincidences.md'
    - 'False alarm probablity of conicidences': 'fap_coincidences.md'
    - 'Followup of interesting outliers': 'followup.md'
    - 'Sensitivity upper limits': 'sensitivity_upper_limits.md'
    - 'Pipeline: a minimal example': 'pipeline_script.md'
    - 'Documents and publications': 'articles.md'

markdown_extensions: ['extra', 'mathjax', 'iconfonts(base=fa,prefix=fa)']

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

